import {
  Plane,
  Car,
  Moon,
  Tent,
  Ship,
  Train,
  Bike,
  Mountain,
  Umbrella,
  Snowflake,
  Building2,
  Home,
  Baby,
  GraduationCap,
  Briefcase,
  Heart,
  Users,
  Backpack,
  Camera,
  Star,
} from 'lucide-react'

/** Lucide icon name → component for template rows & picker */
export const TEMPLATE_ICON_COMPONENTS = {
  Plane,
  Car,
  Moon,
  Tent,
  Ship,
  Train,
  Bike,
  Mountain,
  Umbrella,
  Snowflake,
  Building: Building2,
  Home,
  Baby,
  GraduationCap,
  Briefcase,
  Heart,
  Users,
  Backpack,
  Camera,
  Star,
}

/** Grid metadata — `name` is persisted on `templates.icon` */
export const TEMPLATE_ICON_PICKER = [
  { name: 'Plane', label: 'Flight' },
  { name: 'Car', label: 'Road trip' },
  { name: 'Moon', label: 'Weekend' },
  { name: 'Tent', label: 'Camping' },
  { name: 'Ship', label: 'Cruise' },
  { name: 'Train', label: 'Train' },
  { name: 'Bike', label: 'Cycling' },
  { name: 'Mountain', label: 'Hiking' },
  { name: 'Umbrella', label: 'Beach' },
  { name: 'Snowflake', label: 'Ski' },
  { name: 'Building', label: 'City' },
  { name: 'Home', label: 'Staycation' },
  { name: 'Baby', label: 'Baby trip' },
  { name: 'GraduationCap', label: 'School trip' },
  { name: 'Briefcase', label: 'Business' },
  { name: 'Heart', label: 'Honeymoon' },
  { name: 'Users', label: 'Group' },
  { name: 'Backpack', label: 'Backpacking' },
  { name: 'Camera', label: 'Photography' },
  { name: 'Star', label: 'Special' },
]
